### ISSUE TITLE
Not working anymore?

### ISSUE THREAD

**Issue by wallyqs** [snormore/cilium-portmap#2]
I tried the following and seems it has stopped being successful for some reason:
```
kubectl apply -f https://raw.githubusercontent.com/snormore/cilium-portmap/master/DaemonSet/daemonset.yaml
```

**Comment by snormore** [comment]
Hey @wallyqs, sorry I didn't see the notification for this until now. I actually just recently added a much simpler way to do this without the need for a new daemonset or init container, instead by just [updating the existing postStart lifecycle hook](https://github.com/snormore/cilium-portmap#include-inline-to-the-container-poststart-lifecycle-hook) on the Cilium daemonset exactly where it would normally be dropping a similar CNI config already.

EDIT: I've also pushed a fix for the daemonset method in case you want to keep using that, tl;dr it was using the wrong volume mount.

----

We 1. tell Cilium not to drop it's own config via the `CILIUM_CNI_CONF` env, and 2. Update the `postStart` lifecycle hook where Cilium does a `/cni-install.sh` already, to include the writing of a CNI config enabling portmap.

```
kubectl edit ds cilium -n kube-system
```

Add this under the container `env`
```yaml
# We drop our own CNI config with portmap enabled, so this tells
# Cilium not to write one.
- name: CILIUM_CNI_CONF
    value: /dev/null
```

Replace this

```yaml
lifecycle:
    postStart:
    exec:
        command:
        - /cni-install.sh
    preStop:
    exec:
        command:
        - /cni-uninstall.sh
```

with

```yaml
lifecycle:
    postStart:
    exec:
        command:
        - sh
        - -c
        - "echo '{\"cniVersion\": \"0.3.1\", \"name\": \"portmap\", \"plugins\": [{\"name\": \"cilium\", \"type\": \"cilium-cni\"}, {\"type\": \"portmap\", \"capabilities\": {\"portMappings\": true}}]}' > /host/etc/cni/net.d/05-cilium.conflist && /cni-install.sh"
    preStop:
    exec:
        command:
        - sh
        - -c
        - "/cni-uninstall.sh && rm /host/etc/cni/net.d/05-cilium.conflist"
```
